version: '3'

services:
  app:
    image: weather.forecast.api:latest
    build: ./WeatherForecast.Api
    ports:
      - 8080:8080
    networks:
      - app
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.1/22
