version: '3'

services:
  app:
    build: ./WeatherForecast.Api
    ports:
      - 8081:8081
    networks:
      - app
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.1/22
